apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: pingpong-vol
          persistentVolumeClaim:
            claimName: exercises-claim
      containers:
        - name: pingpong
          image: ping_pong:2.7
          env:
            - name: POSTGRES_HOST
              value: pingpong-postgres-svc
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: postgres-credentials
                   key: password
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_SSLMODE
              value: disable
          volumeMounts:
            - name: pingpong-vol
              mountPath: /usr/src/app/logs
