apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: pingpong-vol
          persistentVolumeClaim:
            claimName: exercises-claim
      containers:
        - name: pingpong
          image: ping_pong:2.1
          volumeMounts:
            - name: pingpong-vol
              mountPath: /usr/src/app/logs
