apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: exercises
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:qXPCv5mwPHr3+KH5,iv:1G5U35heZLbaz58+MdEQx1Q2nACwz/ejnDO3NzJm2Hs=,tag:SFdxA83fbKaEdIBD/fxlLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MTZ3L1ZSSVVodXk3Y3li
            V3BXa2k3bW82bzE4WWFoTDUyekF4bnZCcFVZCjNIWGxXMGxNNXNsR2NrRXRmMUZ0
            YzN0OXZSb3hVRVBXcGJBSkx5UmJTQ0EKLS0tIDFpeXlEcGRWb1ZyeGRRdG9yK1J0
            NTNjZkdqbldFQTlHcER3T2tCc3NqNGsKy8w76U2O2s3iQwz2B/NXhR+hqa8nTqq8
            DjYl8ZC1ickfzc3BOKmW6kg/hQz9zqJjHsFBOFyPjZzOC5F2dPPFcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h000yhpmdxupzn5dl5uv07yahl0euw98e44d8lpmunr8mtun3ejqh4vmjc
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-08-22T07:09:22Z"
    mac: ENC[AES256_GCM,data:WOSnGHeq6MDXTititT6EnYBnUyDKNEV0u6bn4yBLJOA+Tt0qgDSA0uUWcPva19ElXe/Ry3FFfQGhmSI5sjcbdDWBJLBsPuMtEk/peF/dV/a/mqQBszusHmxHQGxAvaxRPrameCQOlmlBP3cbfB0ytQvQ/hv8Rfb+VSd6PaL4nq8=,iv:AedkCmvXTyyYyd9CFg6T7eUEomnYnBH6RyuFLe+UTuY=,tag:zcwTfN8V/r4VQskvlGUCmg==,type:str]
    version: 3.13.3
