apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: logs-generator
          image: logs_generator:1.10
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/logs
        - name: logs-reader
          image: logs_reader:1.10
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/logs
