apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: exercises-claim
      containers:
        - name: logs-generator
          image: logs_generator:2.1
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/logs
        - name: logs-reader
          image: logs_reader:2.1
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/logs
          env:
            - name: PINGPONG_SVC_NAME
              value: "pingpong-svc"
            - name: PINGPONG_SVC_PORT
              value: "4567"
